### ISSUE TITLE
How to use ray to train in deepbots environment.

### ISSUE THREAD

**Issue by cwjwudi** [aidudezzz/deepbots#97]
Hello, when Something is wrong when I try to use the RLlib to train in deepbots environment. I found that your group is also try to use the ray or stable base-line to train. Could you give me some advice to use ray in the deepbots environment. Thank you very much.

```
2021-09-24 15:06:42,723 ERROR trial_runner.py:773 -- Trial SAC_M02RobotSupervisor_f7f86_00000: Error processing event.
Traceback (most recent call last):
  File "/home/cwj/miniconda3/envs/rllib/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 739, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/cwj/miniconda3/envs/rllib/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 746, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/cwj/miniconda3/envs/rllib/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/home/cwj/miniconda3/envs/rllib/lib/python3.7/site-packages/ray/worker.py", line 1623, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::SAC.__init__() (pid=40915, ip=192.168.50.170)
  File "/home/cwj/miniconda3/envs/rllib/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 136, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/home/cwj/miniconda3/envs/rllib/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 592, in __init__
    super().__init__(config, logger_creator)
  File "/home/cwj/miniconda3/envs/rllib/lib/python3.7/site-packages/ray/tune/trainable.py", line 103, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/cwj/miniconda3/envs/rllib/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 146, in setup
    super().setup(config)
  File "/home/cwj/miniconda3/envs/rllib/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 739, in setup
    self._init(self.config, self.env_creator)
  File "/home/cwj/miniconda3/envs/rllib/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 175, in _init
    num_workers=self.config["num_workers"])
  File "/home/cwj/miniconda3/envs/rllib/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 827, in _make_workers
    logdir=self.logdir)
  File "/home/cwj/miniconda3/envs/rllib/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 111, in __init__
    spaces=spaces,
  File "/home/cwj/miniconda3/envs/rllib/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 440, in _make_worker
    spaces=spaces,
  File "/home/cwj/miniconda3/envs/rllib/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 401, in __init__
    self.env = env_creator(env_context)
  File "/home/cwj/miniconda3/envs/rllib/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 1647, in <lambda>
    register_env(name, lambda config: env_object(config))`
```

**Comment by KelvinYang0320** [comment]
@cwjwudi Hi, one of the PR opened by @NickKok is related to `ray` . 
You could check this [deepworlds example](https://github.com/eellak-gsoc2021/deepbots-stable/tree/dev/examples/khr-3hv#khr-3hv-robot-supervisor-tutorial) to see if it helps.

**Comment by cwjwudi** [comment]
> @cwjwudi Hi, one of the PR opened by @NickKok is related to `ray` .
> You could check this [deepworlds example](https://github.com/eellak-gsoc2021/deepbots-stable/tree/dev/examples/khr-3hv#khr-3hv-robot-supervisor-tutorial) to see if it helps.

Thank you for your help.  That's very helpful!

**Comment by tsampazk** [comment]
Assigned to @NickKok
